sudo: required

language: python

python:
  - "3.6"

services:
- docker

# command to install dependencies
install:
  - pip install -r requirements.txt
# command to run tests


before_script:
  - pytest


script:
  - if [ "$TRAVIS_BRANCH" != "master"  ]; then docker build -t ramrodpcp/database-brain:$TRAVIS_BRANCH . ; else docker build -t ramrodpcp/database-brain:latest . ; fi
  - if [ "$TRAVIS_BRANCH" != "master"  ]; then docker run -d --rm --name Brain -e "STAGE=DEV" -e "LOGLEVEL=DEBUG" -v /var/run/docker.sock:/var/run/docker.sock ramrodpcp/database-brain:$TRAVIS_BRANCH ; else docker run -d --rm --name Brain -e "STAGE=PROD" -e "LOGLEVEL=CRITICAL" -v /var/run/docker.sock:/var/run/docker.sock ramrodpcp/database-brain:latest ; fi
  - sleep 30
  - docker ps
  - docker logs Brain
  - docker stop Brain

after_success:
  - if [ "$TRAVIS_BRANCH" = "qa"  ] || [ "$TRAVIS_BRANCH" = "master"  ]; then echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin; fi
  - if [ "$TRAVIS_BRANCH" = "qa"  ]; then docker push ramrodpcp/database-brain:$TRAVIS_BRANCH; fi
  - if [ "$TRAVIS_BRANCH" = "master"  ]; then docker push ramrodpcp/database-brain:latest; fi


slack: ramrod-project:GDF82rRYDg3KSekrT3GA24qO
